defaults:
  environment: &env
    TRAVIS_BRANCH: $CIRCLE_BRANCH
    TRAVIS_PULL_REQUEST: $CI_PULL_REQUEST || "false"
  steps: &ci_steps
    - checkout
    - run: bin/ci prepare_system
    - run: bin/ci prepare_build
    - run: bin/ci build

version: 2

jobs:
  build_linux:
    machine: true
    environment:
      <<: *env
      TRAVIS_OS_NAME: linux
      ARCH: x86_64
      ARCH_CMD: linux64
    steps: *ci_steps

  build_linux32:
    machine: true
    environment:
      <<: *env
      TRAVIS_OS_NAME: linux
      ARCH: i386
      ARCH_CMD: linux32
      ARCH_LIBRARY_PATH: /opt/crystal/embedded/lib/
    steps: *ci_steps

  build_darwin:
    macos:
      xcode: "9.0"
    environment:
      <<: *env
      TRAVIS_OS_NAME: osx
    steps: *ci_steps

  dist_packages_linux:
    machine: true
    steps:
      - run: |
          git clone https://github.com/bcardiff/distribution-scripts.git ~/distribution-scripts
          cd ~/distribution-scripts
          git checkout params
          cd x86_64
          make CRYSTAL_VERSION=nightly CRYSTAL_SHA1=$CIRCLE_SHA1 release=true
      - store_artifacts:
          path: ~/distribution-scripts/x86_64/build
          destination: dist_packages

  dist_packages_darwin:
    macos:
      xcode: "9.0"
    shell: /bin/bash --login
    steps:
      - run:
          name: Set Ruby Version
          command:  echo "2.4.2" > ~/.ruby-version
      - run: |
          sudo mkdir -p /opt/crystal
          sudo chown $(whoami) /opt/crystal/
          sudo mkdir -p /var/cache
          sudo chown $(whoami) /var/cache

          git clone https://github.com/bcardiff/distribution-scripts.git ~/distribution-scripts
          cd ~/distribution-scripts
          git checkout params
          cd omnibus
          bundle check || bundle install --binstubs
          cd ../x86_64
          make darwin CRYSTAL_VERSION=nightly CRYSTAL_SHA1=$CIRCLE_SHA1 release=true
      - store_artifacts:
          path: ~/distribution-scripts/x86_64/build
          destination: dist_packages

workflows:
  version: 2
  build_all_platforms:
    jobs:
      - build_linux:
          filters: &ci_filter
            branches:
              only:
                - master
                - /release\/.+/
                - /.*\bci\b.*/
            tags:
              only: /.*/
      - build_linux32:
          filters: *ci_filter
      - build_darwin:
          filters: *ci_filter
      - dist_packages_linux:
          filters: &nightly_filter
            branches:
              only:
                - ci/nightly
      - dist_packages_darwin:
          filters: *nightly_filter

